/*
 * This file is generated by jOOQ.
 */
package com.ygor.springbootjooq.domain;


import com.ygor.springbootjooq.domain.tables.Comments;
import com.ygor.springbootjooq.domain.tables.Posts;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.comments</code>.
     */
    public static final Comments COMMENTS = com.ygor.springbootjooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = com.ygor.springbootjooq.domain.tables.Posts.POSTS;
}
